[2025-08-03 20:03:32 -0700] [35932] [INFO] Starting gunicorn 23.0.0
[2025-08-03 20:03:32 -0700] [35932] [ERROR] Connection in use: ('0.0.0.0', 8080)
[2025-08-03 20:03:32 -0700] [35932] [ERROR] connection to ('0.0.0.0', 8080) failed: [Errno 98] Address already in use
[2025-08-03 20:03:33 -0700] [35932] [ERROR] Connection in use: ('0.0.0.0', 8080)
[2025-08-03 20:03:33 -0700] [35932] [ERROR] connection to ('0.0.0.0', 8080) failed: [Errno 98] Address already in use
[2025-08-03 20:03:34 -0700] [35932] [ERROR] Connection in use: ('0.0.0.0', 8080)
[2025-08-03 20:03:34 -0700] [35932] [ERROR] connection to ('0.0.0.0', 8080) failed: [Errno 98] Address already in use
[2025-08-03 20:03:35 -0700] [35932] [ERROR] Connection in use: ('0.0.0.0', 8080)
[2025-08-03 20:03:35 -0700] [35932] [ERROR] connection to ('0.0.0.0', 8080) failed: [Errno 98] Address already in use
[2025-08-03 20:03:36 -0700] [35932] [ERROR] Connection in use: ('0.0.0.0', 8080)
[2025-08-03 20:03:36 -0700] [35932] [ERROR] connection to ('0.0.0.0', 8080) failed: [Errno 98] Address already in use
[2025-08-03 20:03:37 -0700] [35932] [ERROR] Can't connect to ('0.0.0.0', 8080)
Running the mlflow server failed. Please see the logs above for details.
